# metrics-instance.yaml
# MetricsInstance – defines the remote_write endpoint (Mimir)
apiVersion: monitoring.grafana.com/v1alpha1
kind: MetricsInstance
metadata:
  name: primary
  namespace: default
  labels:
    agent: grafana-agent-metrics
spec:
  remoteWrite:
    - url: http://mimir-nginx.mimir.svc.cluster.local/api/v1/push
      headers:
        X-Scope-OrgID: anonymous
  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector:
    matchLabels:
      instance: primary
